spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pms?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd hh:mm:ss
