#配置应用服务的名称和端口
spring:
  application:
    name: gateway
server:
  port: 9000
#配置注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
#Zuul路由的默认访问规则是：
  #http://端口号//应用服务名称
  #可以修改为自定义方式:zuul: routes: /目标应用服务名称/**
zuul:
  routes:
    client: /myclient/**
#当使用网关时，设置服务降级等待时间
ribbon:
  ReadTimeout: 1000
  ConnectTimeout: 1000