#1.\u6570\u636E\u6E90\u914D\u7F6E
#2.\u914D\u7F6Emybatis\u7684\u6620\u5C04\u6587\u4EF6\u4F4D\u7F6E\u548C\u5F00\u542F\u9A7C\u5CF0\u547D\u540D\u89C4\u5219
#3.\u914D\u7F6Epagehelper
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://101.132.157.159:3306/jqgriddemo?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: pageNum=currentPage,pageSize=pageSize
  reasonable: true
logging:
  level:
    com:
      woniuxy:
        jqgriddemo:
          dao: debug