#配置内容
#1.配置服务器
#2.配置thymeleaf缓存
#3.配置数据源（mysql）
#4.配置返回前端的日期各式
#5.配置分页插件pagehelper
#6.配置映射文件位置
#7.配置日志输出信息
#8.定义文件路径
#配置服务器:端口8080,访问路径
server:
  port: 8080
  servlet:
    context-path: /
#配置thymeleaf缓存取消
spring:
  thymeleaf:
    cache: false
  #配置数据源
  #注意：由于使用的的驱动为8.0+的版本，需要设置时区(serverTimezone=GMT+8)。并且需要对+号进行转义
  datasource:
    url: jdbc:mysql://localhost:3306/season04?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  #配置返回前端的日期各式
#  mvc:
#    date-format: yyyy-MM-dd
#  jackson:
#    date-format: yyyy-MM-dd
#配置分页插件
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: pageNum=currentPage,pageSize=pageSize
#配置映射文件位置
mybatis:
  mapper-locations: classpath:/mapper/*.xml
#配置日志输出信息
logging:
  level:
    com.example.demo.mapper: debug
#定义文件路径
filepath: E:\fileUpload