server:
  port: 8080
  servlet:
    context-path: /
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    date-format: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: pageNum=currentPage,pageSize=pageSize
mybatis:
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    com.woniu.demo.dao: debug
filepath: /usr/local/upload








